In [4]:
#!/c/Apps/Anaconda3/python
# -*- coding: utf-8 -*-
"""
[Title] Histogram
[Author] Yibeck Lee(yibec.Lee@gmail.com)
[Contents] 
 - Histogram & Descriptive Statistics(기술통계)
"""
# %matplotlib inline
import pandas as pd

df = pd.read_csv("WIP_HISTORY.csv")

print('\n[df.info()]')
print(df.info())

[df.info()]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
TARGET_VALUE    10000 non-null int64
GOOD_BAD        10000 non-null int64
LINE            10000 non-null int64
EQUIPMENT       10000 non-null int64
GAS_PRESSURE    10000 non-null int64
TEMPERATURE     10000 non-null int64
THICKNESS       10000 non-null int64
WAITING_TIME    10000 non-null int64
PROCESS_TIME    10000 non-null int64
INTENSITY       10000 non-null int64
RPM             10000 non-null int64
TIME_GAP        10000 non-null int64
SPEED           10000 non-null int64
dtypes: int64(13)
memory usage: 1015.7 KB
None

In [12]:
print(list(df))

print('\n[df.columns]')
print(df.columns)


print('\n[df.columns --> list]')
column_list = df.columns.tolist()
print(column_list,'\n')
print('[type(column_list)]', type(column_list))

['TARGET_VALUE', 'GOOD_BAD', 'LINE', 'EQUIPMENT', 'GAS_PRESSURE', 'TEMPERATURE', 'THICKNESS', 'WAITING_TIME', 'PROCESS_TIME', 'INTENSITY', 'RPM', 'TIME_GAP', 'SPEED']

[df.columns]
Index(['TARGET_VALUE', 'GOOD_BAD', 'LINE', 'EQUIPMENT', 'GAS_PRESSURE',
       'TEMPERATURE', 'THICKNESS', 'WAITING_TIME', 'PROCESS_TIME', 'INTENSITY',
       'RPM', 'TIME_GAP', 'SPEED'],
      dtype='object')

[df.columns --> list]
['TARGET_VALUE', 'GOOD_BAD', 'LINE', 'EQUIPMENT', 'GAS_PRESSURE', 'TEMPERATURE', 'THICKNESS', 'WAITING_TIME', 'PROCESS_TIME', 'INTENSITY', 'RPM', 'TIME_GAP', 'SPEED']

[type(column_list)] <class 'list'>

In [8]:
print('[df.head')
df.head(10)

[df.head

,TARGET_VALUE,GOOD_BAD,LINE,EQUIPMENT,GAS_PRESSURE,TEMPERATURE,THICKNESS,WAITING_TIME,PROCESS_TIME,INTENSITY,RPM,TIME_GAP,SPEED
0,80952,0,3,2,59,10795,1019,1029,7630,221,41427250,19,9582
1,75331,1,2,3,188,11134,919,851,2190,298,85665341,3,9324
2,78700,0,3,4,218,10989,1122,1040,735,352,93349597,26,9346
3,81604,1,2,3,39,10394,1111,1000,14384,339,21834,77643,9662
4,80520,0,1,2,273,10377,1411,817,7154,171,145584,211274,9081
5,78577,0,3,4,301,11238,1195,1049,8154,120,108783,23,9363
6,79811,1,2,3,178,11304,1258,1082,9460,175,12701568,18708,9374
7,79379,0,2,2,313,10886,862,1010,4648,156,112248,131661,9652
8,85541,1,2,4,103,10571,1285,1028,7473,338,78341268,60,9039
9,78027,0,3,2,324,10917,1211,979,7950,51,152809,52,9307

In [9]:
print('[df.tail')
df.tail(10)

[df.tail

,TARGET_VALUE,GOOD_BAD,LINE,EQUIPMENT,GAS_PRESSURE,TEMPERATURE,THICKNESS,WAITING_TIME,PROCESS_TIME,INTENSITY,RPM,TIME_GAP,SPEED
9990,86805,0,3,4,319,10821,1093,1035,3685,294,30281,2264,9549
9991,85102,0,3,2,8,10818,1166,1018,9507,344,62198,1371,9179
9992,69355,0,3,2,312,10965,1151,1068,3548,65,12823,155776,8868
9993,75292,0,3,4,129,10332,1383,761,961,151,69047,45158,9031
9994,85323,1,2,3,187,10165,1122,1042,4798,321,115649,85553,9931
9995,77676,0,3,2,73,11831,905,1014,3419,183,63957241,87,9308
9996,78857,0,1,2,26,10773,1122,1010,2783,230,147901,30455,9198
9997,87380,0,3,1,20,10128,1297,1055,5823,43,23482888,23,9585
9998,78485,0,1,2,122,11094,1081,1064,5622,66,96686,57363,8824
9999,72473,0,3,2,305,11220,994,1027,204,87,84354,1880,8994